package org.example.model.Regles;

public enum Jeton{
    AUCUN,NOMBRE,
    PIECE, JOUEUR, CASE, PIECETOKEN,
    ACTION, ETAT, COMPTEUR,
    COMPARAISON, ET, OU, CONSEQUENCE,NON,

    ALORS,CONSEQUENCETERMINALE,CONSEQUENCEACTION,ALIAS
}
